import Head from 'next/head';
import EventList from '../components/events/EventList';
import { getFeaturedEvents } from '../dummy-data';

export default function Home() {
	const featuredEvents = getFeaturedEvents();
	return (
		<div>
			<Head>
				<title>Next Events | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="heading">Featured Events</h1>
			<EventList items={featuredEvents} />
		</div>
	);
}
