import Head from 'next/head';
import NewsletterRegistration from '../components/input/NewsletterRegistration';
import EventList from '../components/events/EventList';

export default function Home({ featuredEvents }) {
	if (!featuredEvents) return <p className="error-message">No Featured Event Found</p>;
	return (
		<div>
			<Head>
				<title>Next Events | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="heading">Featured Events</h1>
			<EventList items={featuredEvents} />
			<NewsletterRegistration />
		</div>
	);
}

export const getStaticProps = async () => {
	const res = await fetch('https://max-s-nextjs-course-default-rtdb.firebaseio.com/events.json');
	const events = await res.json();
	const featuredEvents = events.filter((event) => event.isFeatured !== false);
	return {
		props: {
			featuredEvents,
		},
		revalidate: 1800,
	};
};
